### ISSUE TITLE
TravincalLeech - Leechers don't TP back to town

### ISSUE THREAD

**Issue by Bonnono** [blizzhackers-d2/d2bot-with-kolbot#8]
The leechers will take leaders TP to back of Travincal but will just sit there after the council is dead and not TP back to town. In the old repository there was a solution posted a few years ago to pastebin but the page has since been taken down/deleted.

Hoping someone has a solution.

**Comment by azer0** [comment]
Try this out. I tested it a little bit.
[TravincalLeech.txt](https://github.com/blizzhackers-d2/d2bot-with-kolbot/files/4111721/TravincalLeech.txt)

**Comment by Bonnono** [comment]
Seems to work good, thank you!
